# Generated by Django 5.1.2 on 2024-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employeeType',
            field=models.CharField(max_length=200, null=True, verbose_name="O'qtuvchi turi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
