# Generated by Django 5.1.2 on 2024-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_employeetype_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
