# Generated by Django 5.1.2 on 2024-11-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamTypes',
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
    ]
