# Generated by Django 5.1.2 on 2024-11-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_delete_examtypes_delete_trainingtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicDegree',
        ),
        migrations.DeleteModel(
            name='Citizenship',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.DeleteModel(
            name='EducationType',
        ),
        migrations.DeleteModel(
            name='EduType',
        ),
        migrations.DeleteModel(
            name='EmployeeStatus',
        ),
        migrations.DeleteModel(
            name='EnterOTMYear',
        ),
        migrations.DeleteModel(
            name='FormOfPayment',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='H_Accommodation',
        ),
        migrations.DeleteModel(
            name='H_Citizenship_type',
        ),
        migrations.DeleteModel(
            name='H_Social_Category',
        ),
        migrations.DeleteModel(
            name='H_Student_Status',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.RemoveField(
            model_name='province',
            name='state',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Scientific',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
