# Generated by Django 5.1.2 on 2024-11-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значения')),
            ],
            options={
                'verbose_name': 'Yulduz',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP manzil')),
                ('recourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.recourse', verbose_name='Resurs')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ratingstar', verbose_name='yulduz')),
            ],
        ),
    ]
