# Generated by Django 5.1.2 on 2024-11-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_ratingstar_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recourse',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='content.sub_category'),
        ),
    ]
