# Generated by Django 5.1.2 on 2024-11-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_reviewrecourse_delete_rating_delete_ratingstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.recourse')),
            ],
        ),
    ]
